version: '3.7'

services:
  github-cards:
    container_name: github-cards
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true 
    stdin_open: true 